### PR TITLE
Docs/improve readme

### PR DESCRIPTION
**Pull request by wadinj**
Hello,

I loved your work and this worked very well for me (ubuntu Bionic Beaver 18.04), I just add a quick wget to have a full script available in the readme and avoid folks to clone the whole repository.

Cheers,
Jonathan

### CODE REVIEW

**Comment by AdnanHodzic** [comment]
@wadinj Hi, first of all thanks for your contribution.

However, I'm bit confused. Why would you download `displaylink-debian.sh` with `wget` when this file is there as part of `displaylink-debian` directory. If you want to update to latest version, you can simply run `git pull`.

Thus could you please elaborate what exactly were you trying to do?

**Comment by wadinj** [comment]
Hi Adnan,

It was just to avoid to clone the git repository to retrieve this file and it lastest version without dealing with git.

**Comment by KeithWilliamsGMIT** [comment]
You could also add the line `chmod -x ./displaylink-debian.sh` after `wget` to grant execute permissions just for completeness.

**Comment by wadinj** [comment]
Updated

**Comment by AdnanHodzic** [comment]
@wadinj looks great, thank you for your contribution

**Comment by wadinj** [comment]
Good point yes,
I stupidly took the command without double check.

**Comment by AdnanHodzic** [comment]
@redjamesg thanks for the heads up, I completely overlooked this.

@wadinj no worries, I fixed the problem. Just make sure you check changes before you push them, you'll find this advice very useful in your future career :)

**Pull request merged**
