### PR TITLE
Add support for Linux Mint 21.3 Virginia

### PR DESCRIPTION
**Pull request by jskalski2024**
Tested on Dell laptop with integrated Intel graphics and i-tec CADUAL4KDOCK docking station.
I had to remove file `/etc/X11/xorg.conf.d/20-displaylink.conf` to make it detect monitors.

### CODE REVIEW

**Comment by leonp5** [comment]
For me it seems to work without removing the `20-displaylink.conf`. Using a ThinkPad T480 with CADUA4KDOCKPDL.

**Comment by jskalski2024** [comment]
> For me it seems to work without removing the `20-displaylink.conf`. Using a ThinkPad T480 with CADUA4KDOCKPDL.

Post what graphics card you have.

I just posted what was a problem on my laptop, in case someone go to PR and search for reason of problems.
My laptop also does not boot when CADUAL4KDOCK is connected to USB. I had same problem with other Dell. If it freezes on Linux Mint loading screen, disconnect docking station and restart laptop.

**Comment by leonp5** [comment]
@jskalski2024 
The ThinkPad has a Intel UHD Graphics 620.
The freezing on boot i detected too in the meanwhile.
Are you sure, that it is connected to the DisplayLink driver? Did you try to boot without the DisplayLink driver installed?
I read, that some Linux kernels have problems with dockingstations and stuck on boot.

**Review by Barabazs — APPROVED** [review]
Thanks 🙏

**Pull request merged**
