### PR TITLE
add Ubuntu Hirsute to install requirements

### PR DESCRIPTION
**Pull request by cruwe**
First, thank you very much for developing the `displaylink-debian` and making it available.

I installed yesterday with the patched version and did not experience any adverse effects so far. If you would like the change to "cool off", I'm prepared to report my experiences again next week.

Thank you

### CODE REVIEW

**Comment by Barabazs** [comment]
Thank you for your contribution.

**Review by Barabazs — CHANGES_REQUESTED** [review]
Can you also update the supported platforms in the README.md please?

**Comment by cruwe** [comment]
Done. I have no knowledge of PopOS, which has similar distro codenames, so I did not touch these. Cheers!

**Comment by Barabazs** [comment]
Thanks you very much!

**Review by Barabazs — APPROVED** [review]

**Pull request merged**
