### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by terabyte**
Helps make things even more obvious for users a la #188

### CODE REVIEW

**Comment by AdnanHodzic** [comment]
@terabyte thanks for your contribution! I definitely agree that we need to make it more obvious that all necessary documentation is there, especially since these changes are coming from your own personal experience.

After reviewing your code, here are some of the changes I would make. If you agree please make them in code and let's merge with master.

**README.md**

line 19 and 25:

```
* **THEN CONSULT THE [Post Install Guide][PostInstall] FOR ADDITIONAL STEPS**
```

I would put this in *italic* and rephrase it a bit:
```
* *After installation has been completed, make sure to consult [Post Install Guide][PostInstall]!*
```

line 29:

```
 **NOTE: Your monitor probably will not work until you perform additional steps described in the [Post Installation Guide][PostInstall].**
```
 
Again, I would go with *italic* here and **bold** only on note part and rephrased it a bit:
```
***Please note:** Your external monitor/s will most likely not work as expected unless you perform additional steps as described in the [Post Installation Guide][PostInstall].*
```

lines 31/32/33 are looking good.

**displaylink-debian.sh**

line 455 and 477:

```
echo -e "\nInstall complete, please reboot then consult the post-install guide to complete the installation"
```

Rephrased it, as you don't have to look into post-install guide to complete the installation. Also included a shortened link to post-install guide which people might find useful.

```
echo -e "\nInstall complete, please reboot to apply the changes.\nAfter reboot, make sure to consult post-install guide! http://bit.ly/2TbZleK" 
```

Let me know once you made the changes, thanks!

**Comment by AdnanHodzic** [comment]
@terabyte any updates on making these changes?

**Comment by AdnanHodzic** [comment]
@terabyte today I included a new debug feature, which ads all necessary information when user is submitting a new issue which should help a lot, i.e: `sudo ./displaylink-debian.sh --debug`

Since I didn't hear from you and there are code conflicts with recent changes, I added some of the documentation changes you mentioned here and mentioned it in last commit message to give you credit.

Regardless, with this said I'll close this MR as all changes that needed to be done were done in meantime.

**Comment by terabyte** [comment]
Hey, sorry I was out for the holidays.  Thanks very much for adopting some of my changes, I think the new debug feature will be helpful too!  Thanks again for your excellent install scripts! =D

**Pull request closed without merging**
